name: Run OpenSupaplex Tests
on:
  push
jobs:
  run-tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prepare build environment
      run: |
        cd linux
        ./ci-prepare.sh
      shell: bash
    - name: Build OpenSupaplex for Linux
      run: |
        cd linux
        ./ci-build.sh
      shell: bash
    - name: Run tests
      run: |
        cd tests
        #/sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX;
        #export SDL_VIDEODRIVER=x11;
        #export DISPLAY=:99.0;
        ./run-tests.rb ../linux/OpenSupaplex-linux/OpenSupaplex > test-results.log
      shell: bash
    - name: Upload test results
      uses: actions/upload-artifact@v1
      with:
        name: test-results
        path: tests/test-results.log
