name: Run OpenSupaplex Tests
on:
  push
jobs:
  run-tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build OpenSupaplex for Linux
      run: |
        cd linux
        ./ci-prepare.sh
        ./ci-build.sh
      shell: bash
    - name: Run tests
      run: |
        ./run-tests.rb ../linux/OpenSupaplex-linux/OpenSupaplex > tests-result.log
      shell: bash
    - name: Upload test results
      uses: actions/upload-artifact@v1
      with:
        name: test-results.log
        path: tests/tests-result.log
